IBX-11474: Deprecated IbexaSetupCommand in favor of `ibexa/cloud` package existence check

diff --git a/resources/platformsh/ibexa-oss/5.0/.platform.app.yaml b/resources/platformsh/ibexa-oss/5.0/.platform.app.yaml
--- a/resources/platformsh/ibexa-oss/5.0/.platform.app.yaml
+++ b/resources/platformsh/ibexa-oss/5.0/.platform.app.yaml
@@ -162,6 +162,15 @@ hooks:
         curl -fs https://get.symfony.com/cloud/configurator | bash
         
         NODE_VERSION=v22.16.0 symfony-build
+        
+        if ! grep -q '"name": "ibexa/cloud"' composer.lock 2>/dev/null; then
+            echo ""
+            echo "ERROR: The package 'ibexa/cloud' is mandatory for Ibexa Cloud deployments."
+            echo "Please install it according to the documentation:"
+            echo "https://doc.ibexa.co/en/5.0/ibexa_cloud/install_on_ibexa_cloud/#1-prepare-configuration-files"
+            echo ""
+            exit 1
+        fi
 
     # Deploy hook, access to services & done once (per cluster, not per node), only mounts are writable at this point
     # Note: Http traffic is paused while this is running, so for prod code this should finish as fast as possible, < 30s
